# 
name: Build and Deploy Android
description: Build and Deploy Android
inputs:
  android-key-jks:
    description: Android Key jks
    required: true
  service-account-key-json:
    description: Service Account Key Json
    required: true
  android-store-password:
    description: Android Store Password
    required: true
  android-key-password:
    description: Android Key Password
    required: true
  android-key-alias:
    description: Android Key Alias
    required: true
runs:
  using: composite
  steps:
    # - name: Setup java 17
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'zulu'
    #     java-version: '17'
    - name: Debug keystore decoding
      shell: bash
      env:
        ENCODED_KEYSTORE: ${{ inputs.android-key-jks }}
      run: |
        echo "Encoded length: ${#ENCODED_KEYSTORE}"
        echo "First 20 characters: ${ENCODED_KEYSTORE:0:20}..."
        echo "Last 20 characters: ...${ENCODED_KEYSTORE: -20}"

    - name: Create upload-key.jks
      shell: bash
      run: echo -n ${{ inputs.android-key-jks }} | base64 -d > flutter_med_supply/android/app/upload-key.jks

    - name: Create service-account-key.json
      shell: bash
      run: echo -n ${{ inputs.service-account-key-json }} | base64 -d > flutter_med_supply/android/service-account-key.json

    - name: Create key.properties
      shell: bash
      run: |
        echo 'storePassword=${{ inputs.android-store-password }}' >> flutter_med_supply/android/key.properties
        echo 'keyPassword=${{ inputs.android-key-password }}' >> flutter_med_supply/android/key.properties
        echo 'keyAlias=${{ inputs.android-key-alias }}' >> flutter_med_supply/android/key.properties
        echo 'storeFile=upload-key.jks' >> flutter_med_supply/android/key.properties

    - name: Setup Flutter
      uses: ./.github/actions/setup-flutter

    - name: Build aab
      shell: bash
      run: cd flutter_med_supply && flutter build appbundle --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./flutter_med_supply/build/app/outputs/bundle/release/app-release.aab

    - name: Upload to Google Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: flutter_med_supply/android/service-account-key.json
        packageName: com.pint_app
        releaseFiles: ./flutter_med_supply/build/app/outputs/bundle/release/app-release.aab
        track: internal
        status: draft