// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/obutora/med_supply_info/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/obutora/med_supply_info/ent/medmaker"
	"github.com/obutora/med_supply_info/ent/medsupply"
	"github.com/obutora/med_supply_info/ent/todo"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MedMaker is the client for interacting with the MedMaker builders.
	MedMaker *MedMakerClient
	// MedSupply is the client for interacting with the MedSupply builders.
	MedSupply *MedSupplyClient
	// Todo is the client for interacting with the Todo builders.
	Todo *TodoClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MedMaker = NewMedMakerClient(c.config)
	c.MedSupply = NewMedSupplyClient(c.config)
	c.Todo = NewTodoClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		MedMaker:  NewMedMakerClient(cfg),
		MedSupply: NewMedSupplyClient(cfg),
		Todo:      NewTodoClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		MedMaker:  NewMedMakerClient(cfg),
		MedSupply: NewMedSupplyClient(cfg),
		Todo:      NewTodoClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MedMaker.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MedMaker.Use(hooks...)
	c.MedSupply.Use(hooks...)
	c.Todo.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.MedMaker.Intercept(interceptors...)
	c.MedSupply.Intercept(interceptors...)
	c.Todo.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MedMakerMutation:
		return c.MedMaker.mutate(ctx, m)
	case *MedSupplyMutation:
		return c.MedSupply.mutate(ctx, m)
	case *TodoMutation:
		return c.Todo.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MedMakerClient is a client for the MedMaker schema.
type MedMakerClient struct {
	config
}

// NewMedMakerClient returns a client for the MedMaker from the given config.
func NewMedMakerClient(c config) *MedMakerClient {
	return &MedMakerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `medmaker.Hooks(f(g(h())))`.
func (c *MedMakerClient) Use(hooks ...Hook) {
	c.hooks.MedMaker = append(c.hooks.MedMaker, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `medmaker.Intercept(f(g(h())))`.
func (c *MedMakerClient) Intercept(interceptors ...Interceptor) {
	c.inters.MedMaker = append(c.inters.MedMaker, interceptors...)
}

// Create returns a builder for creating a MedMaker entity.
func (c *MedMakerClient) Create() *MedMakerCreate {
	mutation := newMedMakerMutation(c.config, OpCreate)
	return &MedMakerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MedMaker entities.
func (c *MedMakerClient) CreateBulk(builders ...*MedMakerCreate) *MedMakerCreateBulk {
	return &MedMakerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MedMakerClient) MapCreateBulk(slice any, setFunc func(*MedMakerCreate, int)) *MedMakerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MedMakerCreateBulk{err: fmt.Errorf("calling to MedMakerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MedMakerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MedMakerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MedMaker.
func (c *MedMakerClient) Update() *MedMakerUpdate {
	mutation := newMedMakerMutation(c.config, OpUpdate)
	return &MedMakerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MedMakerClient) UpdateOne(mm *MedMaker) *MedMakerUpdateOne {
	mutation := newMedMakerMutation(c.config, OpUpdateOne, withMedMaker(mm))
	return &MedMakerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MedMakerClient) UpdateOneID(id int) *MedMakerUpdateOne {
	mutation := newMedMakerMutation(c.config, OpUpdateOne, withMedMakerID(id))
	return &MedMakerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MedMaker.
func (c *MedMakerClient) Delete() *MedMakerDelete {
	mutation := newMedMakerMutation(c.config, OpDelete)
	return &MedMakerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MedMakerClient) DeleteOne(mm *MedMaker) *MedMakerDeleteOne {
	return c.DeleteOneID(mm.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MedMakerClient) DeleteOneID(id int) *MedMakerDeleteOne {
	builder := c.Delete().Where(medmaker.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MedMakerDeleteOne{builder}
}

// Query returns a query builder for MedMaker.
func (c *MedMakerClient) Query() *MedMakerQuery {
	return &MedMakerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMedMaker},
		inters: c.Interceptors(),
	}
}

// Get returns a MedMaker entity by its id.
func (c *MedMakerClient) Get(ctx context.Context, id int) (*MedMaker, error) {
	return c.Query().Where(medmaker.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MedMakerClient) GetX(ctx context.Context, id int) *MedMaker {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MedMakerClient) Hooks() []Hook {
	return c.hooks.MedMaker
}

// Interceptors returns the client interceptors.
func (c *MedMakerClient) Interceptors() []Interceptor {
	return c.inters.MedMaker
}

func (c *MedMakerClient) mutate(ctx context.Context, m *MedMakerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MedMakerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MedMakerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MedMakerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MedMakerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MedMaker mutation op: %q", m.Op())
	}
}

// MedSupplyClient is a client for the MedSupply schema.
type MedSupplyClient struct {
	config
}

// NewMedSupplyClient returns a client for the MedSupply from the given config.
func NewMedSupplyClient(c config) *MedSupplyClient {
	return &MedSupplyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `medsupply.Hooks(f(g(h())))`.
func (c *MedSupplyClient) Use(hooks ...Hook) {
	c.hooks.MedSupply = append(c.hooks.MedSupply, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `medsupply.Intercept(f(g(h())))`.
func (c *MedSupplyClient) Intercept(interceptors ...Interceptor) {
	c.inters.MedSupply = append(c.inters.MedSupply, interceptors...)
}

// Create returns a builder for creating a MedSupply entity.
func (c *MedSupplyClient) Create() *MedSupplyCreate {
	mutation := newMedSupplyMutation(c.config, OpCreate)
	return &MedSupplyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MedSupply entities.
func (c *MedSupplyClient) CreateBulk(builders ...*MedSupplyCreate) *MedSupplyCreateBulk {
	return &MedSupplyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MedSupplyClient) MapCreateBulk(slice any, setFunc func(*MedSupplyCreate, int)) *MedSupplyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MedSupplyCreateBulk{err: fmt.Errorf("calling to MedSupplyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MedSupplyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MedSupplyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MedSupply.
func (c *MedSupplyClient) Update() *MedSupplyUpdate {
	mutation := newMedSupplyMutation(c.config, OpUpdate)
	return &MedSupplyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MedSupplyClient) UpdateOne(ms *MedSupply) *MedSupplyUpdateOne {
	mutation := newMedSupplyMutation(c.config, OpUpdateOne, withMedSupply(ms))
	return &MedSupplyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MedSupplyClient) UpdateOneID(id int) *MedSupplyUpdateOne {
	mutation := newMedSupplyMutation(c.config, OpUpdateOne, withMedSupplyID(id))
	return &MedSupplyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MedSupply.
func (c *MedSupplyClient) Delete() *MedSupplyDelete {
	mutation := newMedSupplyMutation(c.config, OpDelete)
	return &MedSupplyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MedSupplyClient) DeleteOne(ms *MedSupply) *MedSupplyDeleteOne {
	return c.DeleteOneID(ms.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MedSupplyClient) DeleteOneID(id int) *MedSupplyDeleteOne {
	builder := c.Delete().Where(medsupply.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MedSupplyDeleteOne{builder}
}

// Query returns a query builder for MedSupply.
func (c *MedSupplyClient) Query() *MedSupplyQuery {
	return &MedSupplyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMedSupply},
		inters: c.Interceptors(),
	}
}

// Get returns a MedSupply entity by its id.
func (c *MedSupplyClient) Get(ctx context.Context, id int) (*MedSupply, error) {
	return c.Query().Where(medsupply.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MedSupplyClient) GetX(ctx context.Context, id int) *MedSupply {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MedSupplyClient) Hooks() []Hook {
	return c.hooks.MedSupply
}

// Interceptors returns the client interceptors.
func (c *MedSupplyClient) Interceptors() []Interceptor {
	return c.inters.MedSupply
}

func (c *MedSupplyClient) mutate(ctx context.Context, m *MedSupplyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MedSupplyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MedSupplyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MedSupplyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MedSupplyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MedSupply mutation op: %q", m.Op())
	}
}

// TodoClient is a client for the Todo schema.
type TodoClient struct {
	config
}

// NewTodoClient returns a client for the Todo from the given config.
func NewTodoClient(c config) *TodoClient {
	return &TodoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `todo.Hooks(f(g(h())))`.
func (c *TodoClient) Use(hooks ...Hook) {
	c.hooks.Todo = append(c.hooks.Todo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `todo.Intercept(f(g(h())))`.
func (c *TodoClient) Intercept(interceptors ...Interceptor) {
	c.inters.Todo = append(c.inters.Todo, interceptors...)
}

// Create returns a builder for creating a Todo entity.
func (c *TodoClient) Create() *TodoCreate {
	mutation := newTodoMutation(c.config, OpCreate)
	return &TodoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Todo entities.
func (c *TodoClient) CreateBulk(builders ...*TodoCreate) *TodoCreateBulk {
	return &TodoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TodoClient) MapCreateBulk(slice any, setFunc func(*TodoCreate, int)) *TodoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TodoCreateBulk{err: fmt.Errorf("calling to TodoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TodoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TodoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Todo.
func (c *TodoClient) Update() *TodoUpdate {
	mutation := newTodoMutation(c.config, OpUpdate)
	return &TodoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TodoClient) UpdateOne(t *Todo) *TodoUpdateOne {
	mutation := newTodoMutation(c.config, OpUpdateOne, withTodo(t))
	return &TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TodoClient) UpdateOneID(id int) *TodoUpdateOne {
	mutation := newTodoMutation(c.config, OpUpdateOne, withTodoID(id))
	return &TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Todo.
func (c *TodoClient) Delete() *TodoDelete {
	mutation := newTodoMutation(c.config, OpDelete)
	return &TodoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TodoClient) DeleteOne(t *Todo) *TodoDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TodoClient) DeleteOneID(id int) *TodoDeleteOne {
	builder := c.Delete().Where(todo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TodoDeleteOne{builder}
}

// Query returns a query builder for Todo.
func (c *TodoClient) Query() *TodoQuery {
	return &TodoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTodo},
		inters: c.Interceptors(),
	}
}

// Get returns a Todo entity by its id.
func (c *TodoClient) Get(ctx context.Context, id int) (*Todo, error) {
	return c.Query().Where(todo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TodoClient) GetX(ctx context.Context, id int) *Todo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TodoClient) Hooks() []Hook {
	return c.hooks.Todo
}

// Interceptors returns the client interceptors.
func (c *TodoClient) Interceptors() []Interceptor {
	return c.inters.Todo
}

func (c *TodoClient) mutate(ctx context.Context, m *TodoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TodoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TodoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TodoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TodoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Todo mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MedMaker, MedSupply, Todo []ent.Hook
	}
	inters struct {
		MedMaker, MedSupply, Todo []ent.Interceptor
	}
)
