// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/obutora/med_supply_info/ent/medmaker"
	"github.com/obutora/med_supply_info/ent/predicate"
)

// MedMakerQuery is the builder for querying MedMaker entities.
type MedMakerQuery struct {
	config
	ctx        *QueryContext
	order      []medmaker.OrderOption
	inters     []Interceptor
	predicates []predicate.MedMaker
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MedMakerQuery builder.
func (mmq *MedMakerQuery) Where(ps ...predicate.MedMaker) *MedMakerQuery {
	mmq.predicates = append(mmq.predicates, ps...)
	return mmq
}

// Limit the number of records to be returned by this query.
func (mmq *MedMakerQuery) Limit(limit int) *MedMakerQuery {
	mmq.ctx.Limit = &limit
	return mmq
}

// Offset to start from.
func (mmq *MedMakerQuery) Offset(offset int) *MedMakerQuery {
	mmq.ctx.Offset = &offset
	return mmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mmq *MedMakerQuery) Unique(unique bool) *MedMakerQuery {
	mmq.ctx.Unique = &unique
	return mmq
}

// Order specifies how the records should be ordered.
func (mmq *MedMakerQuery) Order(o ...medmaker.OrderOption) *MedMakerQuery {
	mmq.order = append(mmq.order, o...)
	return mmq
}

// First returns the first MedMaker entity from the query.
// Returns a *NotFoundError when no MedMaker was found.
func (mmq *MedMakerQuery) First(ctx context.Context) (*MedMaker, error) {
	nodes, err := mmq.Limit(1).All(setContextOp(ctx, mmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{medmaker.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mmq *MedMakerQuery) FirstX(ctx context.Context) *MedMaker {
	node, err := mmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MedMaker ID from the query.
// Returns a *NotFoundError when no MedMaker ID was found.
func (mmq *MedMakerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(1).IDs(setContextOp(ctx, mmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{medmaker.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mmq *MedMakerQuery) FirstIDX(ctx context.Context) int {
	id, err := mmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MedMaker entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MedMaker entity is found.
// Returns a *NotFoundError when no MedMaker entities are found.
func (mmq *MedMakerQuery) Only(ctx context.Context) (*MedMaker, error) {
	nodes, err := mmq.Limit(2).All(setContextOp(ctx, mmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{medmaker.Label}
	default:
		return nil, &NotSingularError{medmaker.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mmq *MedMakerQuery) OnlyX(ctx context.Context) *MedMaker {
	node, err := mmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MedMaker ID in the query.
// Returns a *NotSingularError when more than one MedMaker ID is found.
// Returns a *NotFoundError when no entities are found.
func (mmq *MedMakerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(2).IDs(setContextOp(ctx, mmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{medmaker.Label}
	default:
		err = &NotSingularError{medmaker.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mmq *MedMakerQuery) OnlyIDX(ctx context.Context) int {
	id, err := mmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MedMakers.
func (mmq *MedMakerQuery) All(ctx context.Context) ([]*MedMaker, error) {
	ctx = setContextOp(ctx, mmq.ctx, "All")
	if err := mmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MedMaker, *MedMakerQuery]()
	return withInterceptors[[]*MedMaker](ctx, mmq, qr, mmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mmq *MedMakerQuery) AllX(ctx context.Context) []*MedMaker {
	nodes, err := mmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MedMaker IDs.
func (mmq *MedMakerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mmq.ctx.Unique == nil && mmq.path != nil {
		mmq.Unique(true)
	}
	ctx = setContextOp(ctx, mmq.ctx, "IDs")
	if err = mmq.Select(medmaker.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mmq *MedMakerQuery) IDsX(ctx context.Context) []int {
	ids, err := mmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mmq *MedMakerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Count")
	if err := mmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mmq, querierCount[*MedMakerQuery](), mmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mmq *MedMakerQuery) CountX(ctx context.Context) int {
	count, err := mmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mmq *MedMakerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Exist")
	switch _, err := mmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mmq *MedMakerQuery) ExistX(ctx context.Context) bool {
	exist, err := mmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MedMakerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mmq *MedMakerQuery) Clone() *MedMakerQuery {
	if mmq == nil {
		return nil
	}
	return &MedMakerQuery{
		config:     mmq.config,
		ctx:        mmq.ctx.Clone(),
		order:      append([]medmaker.OrderOption{}, mmq.order...),
		inters:     append([]Interceptor{}, mmq.inters...),
		predicates: append([]predicate.MedMaker{}, mmq.predicates...),
		// clone intermediate query.
		sql:  mmq.sql.Clone(),
		path: mmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MedMaker.Query().
//		GroupBy(medmaker.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mmq *MedMakerQuery) GroupBy(field string, fields ...string) *MedMakerGroupBy {
	mmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MedMakerGroupBy{build: mmq}
	grbuild.flds = &mmq.ctx.Fields
	grbuild.label = medmaker.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.MedMaker.Query().
//		Select(medmaker.FieldName).
//		Scan(ctx, &v)
func (mmq *MedMakerQuery) Select(fields ...string) *MedMakerSelect {
	mmq.ctx.Fields = append(mmq.ctx.Fields, fields...)
	sbuild := &MedMakerSelect{MedMakerQuery: mmq}
	sbuild.label = medmaker.Label
	sbuild.flds, sbuild.scan = &mmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MedMakerSelect configured with the given aggregations.
func (mmq *MedMakerQuery) Aggregate(fns ...AggregateFunc) *MedMakerSelect {
	return mmq.Select().Aggregate(fns...)
}

func (mmq *MedMakerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mmq); err != nil {
				return err
			}
		}
	}
	for _, f := range mmq.ctx.Fields {
		if !medmaker.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mmq.path != nil {
		prev, err := mmq.path(ctx)
		if err != nil {
			return err
		}
		mmq.sql = prev
	}
	return nil
}

func (mmq *MedMakerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MedMaker, error) {
	var (
		nodes = []*MedMaker{}
		_spec = mmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MedMaker).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MedMaker{config: mmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mmq *MedMakerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mmq.querySpec()
	_spec.Node.Columns = mmq.ctx.Fields
	if len(mmq.ctx.Fields) > 0 {
		_spec.Unique = mmq.ctx.Unique != nil && *mmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mmq.driver, _spec)
}

func (mmq *MedMakerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(medmaker.Table, medmaker.Columns, sqlgraph.NewFieldSpec(medmaker.FieldID, field.TypeInt))
	_spec.From = mmq.sql
	if unique := mmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mmq.path != nil {
		_spec.Unique = true
	}
	if fields := mmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, medmaker.FieldID)
		for i := range fields {
			if fields[i] != medmaker.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mmq *MedMakerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mmq.driver.Dialect())
	t1 := builder.Table(medmaker.Table)
	columns := mmq.ctx.Fields
	if len(columns) == 0 {
		columns = medmaker.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mmq.sql != nil {
		selector = mmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mmq.ctx.Unique != nil && *mmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mmq.predicates {
		p(selector)
	}
	for _, p := range mmq.order {
		p(selector)
	}
	if offset := mmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MedMakerGroupBy is the group-by builder for MedMaker entities.
type MedMakerGroupBy struct {
	selector
	build *MedMakerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mmgb *MedMakerGroupBy) Aggregate(fns ...AggregateFunc) *MedMakerGroupBy {
	mmgb.fns = append(mmgb.fns, fns...)
	return mmgb
}

// Scan applies the selector query and scans the result into the given value.
func (mmgb *MedMakerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mmgb.build.ctx, "GroupBy")
	if err := mmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedMakerQuery, *MedMakerGroupBy](ctx, mmgb.build, mmgb, mmgb.build.inters, v)
}

func (mmgb *MedMakerGroupBy) sqlScan(ctx context.Context, root *MedMakerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mmgb.fns))
	for _, fn := range mmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mmgb.flds)+len(mmgb.fns))
		for _, f := range *mmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MedMakerSelect is the builder for selecting fields of MedMaker entities.
type MedMakerSelect struct {
	*MedMakerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mms *MedMakerSelect) Aggregate(fns ...AggregateFunc) *MedMakerSelect {
	mms.fns = append(mms.fns, fns...)
	return mms
}

// Scan applies the selector query and scans the result into the given value.
func (mms *MedMakerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mms.ctx, "Select")
	if err := mms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedMakerQuery, *MedMakerSelect](ctx, mms.MedMakerQuery, mms, mms.inters, v)
}

func (mms *MedMakerSelect) sqlScan(ctx context.Context, root *MedMakerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mms.fns))
	for _, fn := range mms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
