// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/obutora/med_supply_info/ent/medsupply"
	"github.com/obutora/med_supply_info/ent/predicate"
)

// MedSupplyQuery is the builder for querying MedSupply entities.
type MedSupplyQuery struct {
	config
	ctx        *QueryContext
	order      []medsupply.OrderOption
	inters     []Interceptor
	predicates []predicate.MedSupply
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MedSupplyQuery builder.
func (msq *MedSupplyQuery) Where(ps ...predicate.MedSupply) *MedSupplyQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit the number of records to be returned by this query.
func (msq *MedSupplyQuery) Limit(limit int) *MedSupplyQuery {
	msq.ctx.Limit = &limit
	return msq
}

// Offset to start from.
func (msq *MedSupplyQuery) Offset(offset int) *MedSupplyQuery {
	msq.ctx.Offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MedSupplyQuery) Unique(unique bool) *MedSupplyQuery {
	msq.ctx.Unique = &unique
	return msq
}

// Order specifies how the records should be ordered.
func (msq *MedSupplyQuery) Order(o ...medsupply.OrderOption) *MedSupplyQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// First returns the first MedSupply entity from the query.
// Returns a *NotFoundError when no MedSupply was found.
func (msq *MedSupplyQuery) First(ctx context.Context) (*MedSupply, error) {
	nodes, err := msq.Limit(1).All(setContextOp(ctx, msq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{medsupply.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MedSupplyQuery) FirstX(ctx context.Context) *MedSupply {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MedSupply ID from the query.
// Returns a *NotFoundError when no MedSupply ID was found.
func (msq *MedSupplyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(setContextOp(ctx, msq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{medsupply.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MedSupplyQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MedSupply entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MedSupply entity is found.
// Returns a *NotFoundError when no MedSupply entities are found.
func (msq *MedSupplyQuery) Only(ctx context.Context) (*MedSupply, error) {
	nodes, err := msq.Limit(2).All(setContextOp(ctx, msq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{medsupply.Label}
	default:
		return nil, &NotSingularError{medsupply.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MedSupplyQuery) OnlyX(ctx context.Context) *MedSupply {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MedSupply ID in the query.
// Returns a *NotSingularError when more than one MedSupply ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MedSupplyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(setContextOp(ctx, msq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{medsupply.Label}
	default:
		err = &NotSingularError{medsupply.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MedSupplyQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MedSupplies.
func (msq *MedSupplyQuery) All(ctx context.Context) ([]*MedSupply, error) {
	ctx = setContextOp(ctx, msq.ctx, "All")
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MedSupply, *MedSupplyQuery]()
	return withInterceptors[[]*MedSupply](ctx, msq, qr, msq.inters)
}

// AllX is like All, but panics if an error occurs.
func (msq *MedSupplyQuery) AllX(ctx context.Context) []*MedSupply {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MedSupply IDs.
func (msq *MedSupplyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if msq.ctx.Unique == nil && msq.path != nil {
		msq.Unique(true)
	}
	ctx = setContextOp(ctx, msq.ctx, "IDs")
	if err = msq.Select(medsupply.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MedSupplyQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MedSupplyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, msq.ctx, "Count")
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, msq, querierCount[*MedSupplyQuery](), msq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MedSupplyQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MedSupplyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, msq.ctx, "Exist")
	switch _, err := msq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MedSupplyQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MedSupplyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MedSupplyQuery) Clone() *MedSupplyQuery {
	if msq == nil {
		return nil
	}
	return &MedSupplyQuery{
		config:     msq.config,
		ctx:        msq.ctx.Clone(),
		order:      append([]medsupply.OrderOption{}, msq.order...),
		inters:     append([]Interceptor{}, msq.inters...),
		predicates: append([]predicate.MedSupply{}, msq.predicates...),
		// clone intermediate query.
		sql:  msq.sql.Clone(),
		path: msq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DoseForm string `json:"dose_form,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MedSupply.Query().
//		GroupBy(medsupply.FieldDoseForm).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MedSupplyQuery) GroupBy(field string, fields ...string) *MedSupplyGroupBy {
	msq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MedSupplyGroupBy{build: msq}
	grbuild.flds = &msq.ctx.Fields
	grbuild.label = medsupply.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DoseForm string `json:"dose_form,omitempty"`
//	}
//
//	client.MedSupply.Query().
//		Select(medsupply.FieldDoseForm).
//		Scan(ctx, &v)
func (msq *MedSupplyQuery) Select(fields ...string) *MedSupplySelect {
	msq.ctx.Fields = append(msq.ctx.Fields, fields...)
	sbuild := &MedSupplySelect{MedSupplyQuery: msq}
	sbuild.label = medsupply.Label
	sbuild.flds, sbuild.scan = &msq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MedSupplySelect configured with the given aggregations.
func (msq *MedSupplyQuery) Aggregate(fns ...AggregateFunc) *MedSupplySelect {
	return msq.Select().Aggregate(fns...)
}

func (msq *MedSupplyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range msq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, msq); err != nil {
				return err
			}
		}
	}
	for _, f := range msq.ctx.Fields {
		if !medsupply.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MedSupplyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MedSupply, error) {
	var (
		nodes = []*MedSupply{}
		_spec = msq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MedSupply).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MedSupply{config: msq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (msq *MedSupplyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.ctx.Fields
	if len(msq.ctx.Fields) > 0 {
		_spec.Unique = msq.ctx.Unique != nil && *msq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MedSupplyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(medsupply.Table, medsupply.Columns, sqlgraph.NewFieldSpec(medsupply.FieldID, field.TypeInt))
	_spec.From = msq.sql
	if unique := msq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if msq.path != nil {
		_spec.Unique = true
	}
	if fields := msq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, medsupply.FieldID)
		for i := range fields {
			if fields[i] != medsupply.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MedSupplyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(medsupply.Table)
	columns := msq.ctx.Fields
	if len(columns) == 0 {
		columns = medsupply.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.ctx.Unique != nil && *msq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MedSupplyGroupBy is the group-by builder for MedSupply entities.
type MedSupplyGroupBy struct {
	selector
	build *MedSupplyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MedSupplyGroupBy) Aggregate(fns ...AggregateFunc) *MedSupplyGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the selector query and scans the result into the given value.
func (msgb *MedSupplyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, msgb.build.ctx, "GroupBy")
	if err := msgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedSupplyQuery, *MedSupplyGroupBy](ctx, msgb.build, msgb, msgb.build.inters, v)
}

func (msgb *MedSupplyGroupBy) sqlScan(ctx context.Context, root *MedSupplyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*msgb.flds)+len(msgb.fns))
		for _, f := range *msgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*msgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MedSupplySelect is the builder for selecting fields of MedSupply entities.
type MedSupplySelect struct {
	*MedSupplyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mss *MedSupplySelect) Aggregate(fns ...AggregateFunc) *MedSupplySelect {
	mss.fns = append(mss.fns, fns...)
	return mss
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MedSupplySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mss.ctx, "Select")
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MedSupplyQuery, *MedSupplySelect](ctx, mss.MedSupplyQuery, mss, mss.inters, v)
}

func (mss *MedSupplySelect) sqlScan(ctx context.Context, root *MedSupplyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mss.fns))
	for _, fn := range mss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
