// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MedMakersColumns holds the columns for the "med_makers" table.
	MedMakersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "favicon_url", Type: field.TypeString},
	}
	// MedMakersTable holds the schema information for the "med_makers" table.
	MedMakersTable = &schema.Table{
		Name:       "med_makers",
		Columns:    MedMakersColumns,
		PrimaryKey: []*schema.Column{MedMakersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "medmaker_name",
				Unique:  true,
				Columns: []*schema.Column{MedMakersColumns[1]},
			},
		},
	}
	// MedSuppliesColumns holds the columns for the "med_supplies" table.
	MedSuppliesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dose_form", Type: field.TypeString},
		{Name: "generic_name", Type: field.TypeString},
		{Name: "unit", Type: field.TypeString},
		{Name: "yj_code", Type: field.TypeString},
		{Name: "yj_base", Type: field.TypeInt},
		{Name: "maker", Type: field.TypeString},
		{Name: "brand_name", Type: field.TypeString},
		{Name: "sales_category", Type: field.TypeString},
		{Name: "shipment_status", Type: field.TypeString},
		{Name: "supply_status", Type: field.TypeString},
		{Name: "expect_lifting_status", Type: field.TypeString},
		{Name: "expect_lifting_description", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MedSuppliesTable holds the schema information for the "med_supplies" table.
	MedSuppliesTable = &schema.Table{
		Name:       "med_supplies",
		Columns:    MedSuppliesColumns,
		PrimaryKey: []*schema.Column{MedSuppliesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "medsupply_yj_base",
				Unique:  false,
				Columns: []*schema.Column{MedSuppliesColumns[5]},
			},
		},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "value", Type: field.TypeInt},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MedMakersTable,
		MedSuppliesTable,
		TodosTable,
	}
)

func init() {
}
