name: Setup Flutter
description: Setup Flutter

runs:
  using: composite

  steps:
    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.22.2
        channel: stable
        cache: true

    - name: Install flutter dependencies
      shell: bash
      run: cd flutter_med_supply && flutter pub get

    # - name: Create .env file
    #   shell: bash
    #   run: |
    #     touch {flutter_med_supply/.env.development,flutter_med_supply/.env}
    #     echo 'DOTMONEY_SECRET_KEY=${{ inputs.dotmoney-secret-key }}' >> flutter_med_supply/.env
    #     echo 'SENTRY_DSN=${{ inputs.sentry-dsn }}' >> flutter_med_supply/.env