// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MedMaker is the predicate function for medmaker builders.
type MedMaker func(*sql.Selector)

// MedSupply is the predicate function for medsupply builders.
type MedSupply func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
